In [28]:
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from statistics import median
import numpy as np
sc = StandardScaler()

df = pd.read_csv('data_train.csv', header=0)

X = df.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,13]]

In [29]:
X.iloc[:,[0]]

         advertiser_id
0                 1909
1                 1909
2                 1898
3                 1999
4                 1935
5                 1930
6                 2088
7                 1637
8                 1867
9                 2133
10                1270
11                1637
12                1270
13                1480
14                1930
15                1480
16                1930
17                1637
18                1431
19                1431
20                1953
21                1403
22                1270
23                2069
24                2080
25                1774
26                1235
27                2030
28                1613
29                1516
...                ...
1816538           2069
1816539           1492
1816540           1999
1816541           1909
1816542           2069
1816543           1930
1816544           1888
1816545           2111
1816546           2030
1816547           1637
1816548           1472
1816549           1637
1816550           1637
1816551           1862
1816552           2137
1816553           1930
1816554           1445
1816555           1778
1816556           1613
1816557           1771
1816558           1864
1816559           1971
1816560           1774
1816561           1897
1816562           1270
1816563           2133
1816564           1774
1816565           1972
1816566           2111
1816567           2111

[1816568 rows x 1 columns]

In [30]:
from sklearn.preprocessing import Imputer

imr = Imputer(missing_values='NaN', strategy='median', axis=0)

imr.fit(X.values)

X_imr = imr.transform(X.values)

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(categorical_features=[0,2,3,4,7])

X_one = ohe.fit_transform(X_imr).toarray()

sc.fit(X_one)

X_std = sc.transform(X_one)

In [31]:
X_std.shape[1]

235

In [32]:
click = df.iloc[:,[14]]

In [33]:
Y = np.ravel(click)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=100.0, random_state=1)
lr.fit(X_std, Y)

In [ ]:
test = pd.read_csv('data_test.csv', header=0)
X_test = test.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,13]]
X_testi = imr.transform(X_test)
X_testo = ohe.transform(X_testi).toarray()
X_tests = sc.transform(X_testo)

In [ ]:
Z = lr.predict_proba(X_tests)[:,1]
Z

In [ ]:
Z.shape[0]

In [ ]:
Z.max()

In [ ]:
fout = open('submission062204.dat','w')

R = Z.shape[0]

i = 0

c = 0

for index in range(R):
    
    t = Z[i]
    
    i += 1
    
    if t > 0.5:
        
        c += 1
        
    fout.write(str(t)+'\n')

fout.close()

In [ ]:
c/R